JointProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', RedirectView.as_view(pattern_name='storageandgo:task_list'), name='home'),
    path('admin/', admin.site.urls),
    path('storageandgo/', include('StorageAndGo.urls', namespace='storageandgo')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', include('StorageAndGo.urls')),
]

StorageAndGo/urls.py
from django.conf.urls import url
from django.urls import path

from .views import *


app_name = "storageandgo"

urlpatterns = [

    path('', redirect_to_home),

    # url(r'login_success/$', views.login_success, name='login_success'),
    # url(r'log_out_success/$', views.logout_view, name='logout_success'),

    # LIST OF TASKS

    path('avaria_list/', AvariaList.as_view(), name="AvariaList"),


    #GESTOR SALA

    path('gestor_home/', ListTasks.as_view(), name='task_list'),
    path('gestor_historial', ListHistoryTasks.as_view(), name='task_history_list'),
    path('gestor_arealizar/', ListTasks.as_view(), name="gestor_arealizar"),
    path('gestor_realizando/', ListRealizing.as_view(), name="gestor_realizando"),
    path('gestor_finalizado/', ListFinalized.as_view(), name="gestor_finalizado"),
    path('gestor_creacion_tarea_operario/', CreateOperatorTaskView, name="CreateOperatorTaskView"),
    path('gestor_creacion_tarea_tecnic/', CreateTecnicTaskView, name="CreateTecnicTaskView"),
    path('pedido/', ManifestoCreate.as_view(), name="CreateManifesto"),


    #SALA

    path('mapa_salas/', mapa_salas, name="mapa_salas"),

    path('afegir_sala/', CreateSalaView, name="afegir_sala"),
    path('sala/<int:pk>/', sala_detail, name='sala_detail'),
    path('sala/<int:pk>/delete', sala_delete, name='sala_delete'),
    path('sala/<int:pk>/modify/',
         SalaModify.as_view(),
         name='modify_sala'),


    #OPERARI

    # path('operari_home/', operari_home, name="operari_home"),
    path('operari_home/', operari_arealitzar, name="operari_home"),
    path('operari_arealizar/', operari_arealitzar, name="operari_arealitzar"),
    path('operari_realizando/', operari_realizando, name="operari_realizando"),
    path('operari_finalizado/', operari_finalizado, name="operari_finalizado"),
    path('operari_notification/', operari_notification, name="operari_notification"),
    path('operari_detall_tasca/<pk>/', operari_detall_tasca, name="operari_detall_tasca"),

    #TECNIC

    # path('tecnics_home/', tecnics_home, name="tecnics_home"),
    path('tecnics_home/', tecnics_arealitzar, name="tecnics_home"),
    path('tecnics_arealizar/', tecnics_arealitzar, name="tecnics_arealizar"),
    path('tecnics_realitzant/', tecnics_realizando, name="tecnics_realizando"),
    path('tecnics_finalizado/', tecnics_finalizado, name="tecnics_finalizado"),
    path('create_averia/', CreateAvariaView, name = "afegir_averia"),
    path('tecnics_detall_tasca/<pk>/', tecnics_detall_tasca, name="tecnics_detall_tasca"),


    #TASKS

    path('unasigned_tasks/',
         ListUnasignedTasks.as_view(),
         name='unasigned_task_list'),

    path('tasks/<int:pk>/assign/',
         TaskUpdate.as_view(),
         name='assign_task'),
    path('tasks/<int:pk>/accept/',
         task_accept,
         name='accept_task'),

    path('tasks/<int:pk>/finish/',
         task_finish,
         name='finish_task'),

    path('tasks/<int:pk>/modify_operator/',
         TaskOperatorModify.as_view(),
         name='modify_operator'),

    path('tasks/<int:pk>/modify_maintenance/',
         TaskMaintenanceModify.as_view(),
         name='modify_maintenance'),

    path('tasks/<int:pk>/modify_avaria/',
         TaskAvariaModify.as_view(),
         name='modify_avaria'),


    #CEO
    path(r'informes/', InformeSla.as_view(), name="informe"),
    path('complets_sla/', complets_sla, name="complets_sla"),
    path('capacitat/', capacitat, name="capacitat"),
    path('complets_mes/', complets_mes, name="complets_mes"),
    path('ceo_historial', ListHistoryTasks.as_view(), name='task_history_list'),
    path('ceo_detall_avaria/<pk>/', ceo_detall_averia, name="ceo_detall_avaria"),
]

StorageAndGo/forms.py
from django.forms import ModelForm
from .models import *


class CreateOperatorTaskForm(ModelForm):
    class Meta:
        model = TaskOperator
        fields = '__all__'


class CreateTecnicTaskForm(ModelForm):
    class Meta:
        model = TaskMaintenance
        fields = '__all__'


class CreateSala(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ('contenidorsInside',)

class CreateAvaria(ModelForm):
    class Meta:
        model = Avaria
        fields = 'object', 'room','high_priority'

StorageAndGo/views.py
# FOR LOADING API
import ctypes

import requests
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.views.generic import ListView, UpdateView, CreateView

from .forms import *
import datetime
import pytz


# Create your views here.

#                                                    Index

# GESTOR SALA

# SALA

# OPERARI

# TECNIC

# TASKS

# CEO

# class TaskUpdate(UpdateView):
#     model = Task
#     fields = ['user']
#     template_name = "form.html"
#
#     def form_valid(self, form):
#         form.instance.sender = self.request.user
#         return super(TaskUpdate, self).form_valid(form)

def logout_view(request):
    logout(request)


@login_required()
def redirect_to_home(request):
    if not request.user.is_authenticated:
        return redirect("/accounts/login/")

    group = User.objects.get(username=request.user).groups.all()[0]

    if group.name == "Ceo":
        return redirect("storageandgo:informe")
    elif group.name == 'Tecnic':
        return redirect("storageandgo:tecnics_home")
    elif group.name == 'Gestor':
        return redirect("storageandgo:task_list")
    elif group.name == 'Operari':
        return redirect("storageandgo:operari_home")


class ManifestoCreate(CreateView):
    model = Manifesto
    fields = ['ref']
    template_name = "form.html"

    def form_valid(self, form):
        form.instance.sender = self.request.user
        ref = form.cleaned_data['ref']

        data = requests.get('https://ourfarms.herokuapp.com/apiRest/REF/?ref=' + ref,
                            auth=('GR3', 'gr3124567890')).json()

        contenidors = []
        if data:
            for contenidor in data[0]['Products']:
                cont = Contenidor(**contenidor)
                cont.save()
                contenidors.append(cont)
                if not data[0]['withdrawal']:
                    createTask(contenidor)
                else:
                    createTask2(contenidor)

            del data[0]['Products']

            man = Manifesto(**data[0])
            man.save()
            for contenidor in contenidors:
                man.products.add(contenidor)

        return redirect(reverse('storageandgo:gestor_arealizar'))


############################################ GESTOR SALA ##############################################################

@login_required()
def gestor_home(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-home.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


def gestor_arealizar(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-a-realizar.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


@login_required()
def gestor_realizando(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-realizando.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


@login_required()
def gestor_finalizado(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-finalizado.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


@login_required()
def mapa_salas(request):
    rooms = Room.objects.all()
    colors ={}
    group = User.objects.get(username=request.user).groups.all()[0]
    i = 1
    for room in rooms:
        if room.contenidorsInside /room.capacity > 0.50:
            colors['color'] = "w3-yellow"
        if room.contenidorsInside /room.capacity > 0.75:
            colors['color'] = "w3-orange"
        if room.contenidorsInside /room.capacity < 0.50:
            colors['color'] = "w3-green"
        i = i +1
    # rendering the template in HttpResponse
    if group.name == "Ceo":
        return render(request, "mapa-salas2.html", {'rooms': rooms})
    return render(request, "mapa-salas.html", {'rooms': rooms})


################################################# SALA ###############################################################


@login_required()
def CreateSalaView(request):
    if request.method == 'POST':
        form = CreateSala(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.save()
            return redirect('storageandgo:mapa_salas')
    else:
        form = CreateSala()
        return render(request, "form.html", {'form': form})


class SalaModify(UpdateView):
    model = Room
    fields = '__all__'
    template_name = "form.html"

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super(SalaModify, self).form_valid(form)


############################################## OPERARI #################################################################


@login_required()
def operari_home(request):
    # getting our template
    template = loader.get_template('Operaris/operari-home.html')

    # rendering the template in HttpResponse
    # return HttpResponse(template.render())
    return render(request, "Operaris/operari-home.html", {})


@login_required()
def operari_arealitzar(request):
    template = loader.get_template('Operaris/operari-a-realitzar.html')

    tasques_operari_a_realitzar = TaskOperator.objects.filter(accepted=False)
    context = {'tasques_operari_a_realitzar': tasques_operari_a_realitzar}

    # return HttpResponse(template.render(context))
    return render(request, "Operaris/operari-a-realitzar.html", context=context)


@login_required()
def operari_realizando(request):
    template = loader.get_template('Operaris/operari-realizando.html')

    tasques_operari_realizando = TaskOperator.objects.filter(accepted=True, finished=False, user=request.user)
    context = {'tasques_operari_realizando': tasques_operari_realizando}

    return render(request, "Operaris/operari-realizando.html", context=context)


@login_required()
def operari_finalizado(request):
    template = loader.get_template('Operaris/operari-finalizado.html')

    tasques_operari_finalizado = TaskOperator.objects.filter(finished=True, user=request.user)
    context = {'tasques_operari_finalizado': tasques_operari_finalizado}

    return render(request, "Operaris/operari-finalizado.html", context=context)


def operari_notification(request):
    current_user = request.user.id
    task = Task.objects.filter(user=current_user, high_priority=True, finished=False)

    if task.exists():
        return HttpResponse(task[0].pk)
    else:
        return HttpResponse("-1")


def operari_detall_tasca(request, pk):
    task = TaskOperator.objects.get(id=pk)
    return render(request, 'Operaris/operari-detall-tasca.html', {'tasca': task})

############################################### TECNIC #################################################################


@login_required()
def tecnics_home(request):
    template = loader.get_template('Tecnics/tecnics-home.html')

    return render(request, "Tecnics/tecnics-home.html")
@login_required()
def CreateAvariaView(request):
    if request.method == 'POST':
        form = CreateAvaria(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.save()
            return redirect('storageandgo:tecnics_home')
    else:
        form = CreateAvaria()
        return render(request, "form_tècnic.html", {'form': form})



class AvariaList(ListView):
    template_name = 'avaria_list.html'

    def get_context_data(self, **kwargs):
        context = super(AvariaList, self).get_context_data(**kwargs)
        avaria = Avaria.objects.filter(accepted=False, user=requests.user)
        context['task_avaria'] = avaria
        return context

    def get_queryset(self):
        queryset = Avaria.objects.filter()

        return queryset


@login_required()
def tecnics_arealitzar(request):
    template = loader.get_template('Tecnics/tecnics-a-realizar.html')

    tasques_tecnics_a_realitzar = TaskMaintenance.objects.filter(accepted=False)
    context = {'tasques_tecnics_a_realitzar': tasques_tecnics_a_realitzar}

    return render(request, "Tecnics/tecnics-a-realizar.html", context=context)


@login_required()
def tecnics_realizando(request):
    template = loader.get_template('Tecnics/tecnics-realizando.html')

    tasques_tecnics_realizando = TaskMaintenance.objects.filter(accepted=True, finished=False, user=request.user)
    context = {'tasques_tecnics_realizando': tasques_tecnics_realizando}

    return render(request, "Tecnics/tecnics-realizando.html", context=context)


@login_required()
def tecnics_finalizado(request):
    template = loader.get_template('Tecnics/tecnics-finalitzades.html')

    tasques_tecnics_finalitzades = TaskMaintenance.objects.filter(finished=True, user=request.user)
    context = {'tasques_tecnics_finalitzades': tasques_tecnics_finalitzades}

    return render(request, "Tecnics/tecnics-finalitzades.html", context=context)


def tecnics_detall_tasca(request, pk):
    task = TaskMaintenance.objects.get(id=pk)
    return render(request, 'Tecnics/tecnics-detall-tasca.html', {'tasca': task})

################################################# TASKS ################################################################
class ListUnasignedTasks(ListView):
    template_name = 'unasigned_task_list.html'

    def get_context_data(self, **kwargs):
        context = super(ListUnasignedTasks, self).get_context_data(**kwargs)
        operator = TaskOperator.objects.filter(user=None)
        maintenance = TaskMaintenance.objects.filter(user=None)
        context['unasigned_operator'] = operator
        context['unasigned_maintenance'] = maintenance
        return context

    def get_queryset(self):

StorageAndGo/templates/Gestor_Sala/gestor-sala-a-realizar.html
{% extends "Gestor_Sala/gestor-sala-home.html" %}
{% block content %}

    <h1 style="display: inline;">OPERARIO - TAREAS A REALIZAR</h1><a href='{% url "storageandgo:CreateOperatorTaskView" %}'><button class="w3-button w3-grey" style="margin-left: 50px; margin-bottom: 20px; width: 100px; height: 40px">NUEVA</button></a>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Producto</th>
                <th style="width:20%; text-align: left">Función</th>
        </tr>

        {% for task in task_operator %}

            <tr>
                <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.pk }}</a></td>
                <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.description }}</a></td>
                <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.product }}</a></td>
                <td><a href='{% url "storageandgo:modify_operator" task.pk %}'><button class="w3-button w3-grey" style="width: 100px; height: 40px">EDITAR</button></a></td>
            </tr>

        {% endfor %}
    </table>

    <h1 style="display: inline; margin-top: 20px;">TÉCNICO - TAREAS A REALIZAR</h1><a href='{% url "storageandgo:CreateTecnicTaskView" %}'><button class="w3-button w3-grey" style="margin-left: 67px; margin-top: 10px; margin-bottom: 20px; width: 100px; height: 40px">NUEVA</button></a>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Sala</th>
                <th style="width:20%; text-align: left">Función</th>
        </tr>
    {% for task in task_maintenance %}
        <tr>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.pk }}</a></td>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.description }}</a></td>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.room }}</a></td>
            <td><a href='{% url "storageandgo:modify_maintenance" task.pk %}'><button class="w3-button w3-grey" style="width: 100px; height: 40px">EDITAR</button></a></td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

StorageAndGo/templates/Gestor_Sala/gestor-sala-finalizado.html
{% extends 'Gestor_Sala/gestor-sala-home.html' %}
{% block content %}

    <h1>OPERARIO - TAREAS FINALIZADAS</h1><br>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Producto</th>
        </tr>
    {% for task in task_operator %}
        <tr>
            <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.pk }}</a></td>
            <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.description }}</a></td>
            <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.product }}</a></td>
        </tr>
    {% endfor %}
    </table>

    <h1>TÉCNICO - TAREAS FINALIZADAS</h1><br>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Sala</th>
        </tr>
    {% for task in task_maintenance %}
        <tr>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.pk }}</a></td>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.description }}</a></td>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.room }}</a></td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

StorageAndGo/templates/Gestor_Sala/gestor-sala-history.html
{% extends "Gestor_Sala/gestor-sala-home.html" %}
{% block content %}


    <h1>HISTORIAL TAREAS OPERADOR</h1><br>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Producto</th>
                <th style="width:20%; text-align: left">Función</th>
        </tr>
    {% for task in task_operator %}
        <tr>
            <td>{{ task.pk }}</td>
            <td>{{ task.description }}</td>
            <td>{{ task.product }}</td>
        </tr>
    {% endfor %}
    </table>

    <h1>HISTORIAL TAREAS MANTENIMIENTO</h1><br>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Producto</th>
                <th style="width:20%; text-align: left">Función</th>
        </tr>
    {% for task in task_maintenance %}
        <tr>
            <td>{{ task.pk }}</td>
            <td>{{ task.description }}</td>
            <td>{{ task.product }}</td>
        </tr>
    {% endfor %}
    </table>

{% endblock %}

StorageAndGo/templates/Gestor_Sala/gestor-sala-home.html
{% extends "home.html" %}
{% block sidebar %}
    <nav class="w3-sidebar w3-red w3-collapse w3-large w3-top" style="vz-index:3; top: 20%; width:250px; height: 80%; font-weight:bold; overflow:auto; overflow-x:hidden" id="mySidebar"><br>
        <a href="javascript:void(0)" onclick="w3_close()" class="w3-button w3-hide-large w3-display-topleft" style="width:100%;font-size:22px">Close Menu</a>
        <div class="w3-container">

            <a href= {% url 'storageandgo:gestor_arealizar' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>A realizar</b></h3></a>
            <a href= {% url 'storageandgo:gestor_realizando' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>Realizando</b></h3></a>
            <a href= {% url 'storageandgo:gestor_finalizado' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>Finalizado</b></h3></a>
            <a href= {% url 'storageandgo:mapa_salas' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>Salas</b></h3></a>
{#            <a href= {% url 'storageandgo:CreateTaskView' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>Añadir tarea</b></h3></a>#}
            <a href= {% url 'storageandgo:CreateManifesto' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>Añadir pedido</b></h3></a>
{#            <a href= {% url 'storageandgo:task_history_list' %}><h3 class="w3-padding-32 w3-button w3-left-align"style="width: 240px"><b>Historial</b></h3></a>#}
        </div>
    </nav>
{% endblock %}

StorageAndGo/templates/Gestor_Sala/gestor-sala-realizando.html
{% extends 'Gestor_Sala/gestor-sala-home.html' %}
{% block content %}

    <h1>OPERARIO - TAREAS REALIZANDO</h1><br>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Producto</th>
                <th style="width:20%; text-align: left">Función</th>
        </tr>
    {% for task in task_operator %}
       <tr>
           <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.pk }}</a></td>
           <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.description }}</a></td>
           <td><a href="{% url 'storageandgo:operari_detall_tasca'  pk=task.pk%}">{{ task.product }}</a></td>
            <td><a href='{% url "storageandgo:finish_task" task.pk %}'><button class="w3-button w3-grey" style="width: 100px; height: 40px">FINALIZAR</button></a></td>
        </tr>

    {% endfor %}
    </table>

    <h1>TÉCNICO - TAREAS REALIZANDO</h1><br>
    <table style="width: 100%">
        <tr>
                <th style="width:20%; text-align: left">Id</th>
                <th style="width:20%; text-align: left">Descripción</th>
                <th style="width:20%; text-align: left">Sala</th>
                <th style="width:20%; text-align: left">Función</th>
        </tr>
    {% for task in task_maintenance %}
        <tr>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.pk }}</a></td>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.description }}</a></td>
            <td><a href="{% url 'storageandgo:tecnics_detall_tasca'  pk=task.pk%}">{{ task.room }}</a></td>
            <td><a href='{% url "storageandgo:finish_task" task.pk %}'><button class="w3-button w3-grey" style="width: 100px; height: 40px">FINALIZAR</button></a></td>
        </tr>

    {% endfor %}
    </table>
{% endblock %}