JointProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('', RedirectView.as_view(pattern_name='storageandgo:task_list'), name='home'),
    path('admin/', admin.site.urls),
    path('storageandgo/', include('StorageAndGo.urls', namespace='storageandgo')),
    path('accounts/', include('django.contrib.auth.urls')),
    # path('', include('StorageAndGo.urls')),
]

StorageAndGo/urls.py
from django.conf.urls import url
from django.urls import path

from .views import *


app_name = "storageandgo"

urlpatterns = [

    path('', redirect_to_home),

    # url(r'login_success/$', views.login_success, name='login_success'),
    # url(r'log_out_success/$', views.logout_view, name='logout_success'),

    # LIST OF TASKS

    path('avaria_list/', AvariaList.as_view(), name="AvariaList"),


    #GESTOR SALA

    path('gestor_home/', ListTasks.as_view(), name='task_list'),
    path('gestor_historial', ListHistoryTasks.as_view(), name='task_history_list'),
    path('gestor_arealizar/', ListTasks.as_view(), name="gestor_arealizar"),
    path('gestor_realizando/', ListRealizing.as_view(), name="gestor_realizando"),
    path('gestor_finalizado/', ListFinalized.as_view(), name="gestor_finalizado"),
    path('gestor_creacion_tarea_operario/', CreateOperatorTaskView, name="CreateOperatorTaskView"),
    path('gestor_creacion_tarea_tecnic/', CreateTecnicTaskView, name="CreateTecnicTaskView"),
    path('pedido/', ManifestoCreate.as_view(), name="CreateManifesto"),


    #SALA

    path('mapa_salas/', mapa_salas, name="mapa_salas"),

    path('afegir_sala/', CreateSalaView, name="afegir_sala"),
    path('sala/<int:pk>/', sala_detail, name='sala_detail'),
    path('sala/<int:pk>/delete', sala_delete, name='sala_delete'),
    path('sala/<int:pk>/modify/',
         SalaModify.as_view(),
         name='modify_sala'),


    #OPERARI

    # path('operari_home/', operari_home, name="operari_home"),
    path('operari_home/', operari_arealitzar, name="operari_home"),
    path('operari_arealizar/', operari_arealitzar, name="operari_arealitzar"),
    path('operari_realizando/', operari_realizando, name="operari_realizando"),
    path('operari_finalizado/', operari_finalizado, name="operari_finalizado"),
    path('operari_notification/', operari_notification, name="operari_notification"),
    path('operari_detall_tasca/<pk>/', operari_detall_tasca, name="operari_detall_tasca"),

    #TECNIC

    # path('tecnics_home/', tecnics_home, name="tecnics_home"),
    path('tecnics_home/', tecnics_arealitzar, name="tecnics_home"),
    path('tecnics_arealizar/', tecnics_arealitzar, name="tecnics_arealizar"),
    path('tecnics_realitzant/', tecnics_realizando, name="tecnics_realizando"),
    path('tecnics_finalizado/', tecnics_finalizado, name="tecnics_finalizado"),
    path('create_averia/', CreateAvariaView, name = "afegir_averia"),
    path('tecnics_detall_tasca/<pk>/', tecnics_detall_tasca, name="tecnics_detall_tasca"),


    #TASKS

    path('unasigned_tasks/',
         ListUnasignedTasks.as_view(),
         name='unasigned_task_list'),

    path('tasks/<int:pk>/assign/',
         TaskUpdate.as_view(),
         name='assign_task'),
    path('tasks/<int:pk>/accept/',
         task_accept,
         name='accept_task'),

    path('tasks/<int:pk>/finish/',
         task_finish,
         name='finish_task'),

    path('tasks/<int:pk>/modify_operator/',
         TaskOperatorModify.as_view(),
         name='modify_operator'),

    path('tasks/<int:pk>/modify_maintenance/',
         TaskMaintenanceModify.as_view(),
         name='modify_maintenance'),

    path('tasks/<int:pk>/modify_avaria/',
         TaskAvariaModify.as_view(),
         name='modify_avaria'),


    #CEO
    path(r'informes/', InformeSla.as_view(), name="informe"),
    path('complets_sla/', complets_sla, name="complets_sla"),
    path('capacitat/', capacitat, name="capacitat"),
    path('complets_mes/', complets_mes, name="complets_mes"),
    path('ceo_historial', ListHistoryTasks.as_view(), name='task_history_list'),
    path('ceo_detall_avaria/<pk>/', ceo_detall_averia, name="ceo_detall_avaria"),
]

StorageAndGo/forms.py
from django.forms import ModelForm
from .models import *


class CreateOperatorTaskForm(ModelForm):
    class Meta:
        model = TaskOperator
        fields = '__all__'


class CreateTecnicTaskForm(ModelForm):
    class Meta:
        model = TaskMaintenance
        fields = '__all__'


class CreateSala(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ('contenidorsInside',)

class CreateAvaria(ModelForm):
    class Meta:
        model = Avaria
        fields = 'object', 'room','high_priority'

StorageAndGo/views.py
# FOR LOADING API
import ctypes

import requests
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template import loader
from django.views.generic import ListView, UpdateView, CreateView

from .forms import *
import datetime
import pytz


# Create your views here.

#                                                    Index

# GESTOR SALA

# SALA

# OPERARI

# TECNIC

# TASKS

# CEO

# class TaskUpdate(UpdateView):
#     model = Task
#     fields = ['user']
#     template_name = "form.html"
#
#     def form_valid(self, form):
#         form.instance.sender = self.request.user
#         return super(TaskUpdate, self).form_valid(form)

def logout_view(request):
    logout(request)


@login_required()
def redirect_to_home(request):
    if not request.user.is_authenticated:
        return redirect("/accounts/login/")

    group = User.objects.get(username=request.user).groups.all()[0]

    if group.name == "Ceo":
        return redirect("storageandgo:informe")
    elif group.name == 'Tecnic':
        return redirect("storageandgo:tecnics_home")
    elif group.name == 'Gestor':
        return redirect("storageandgo:task_list")
    elif group.name == 'Operari':
        return redirect("storageandgo:operari_home")


class ManifestoCreate(CreateView):
    model = Manifesto
    fields = ['ref']
    template_name = "form.html"

    def form_valid(self, form):
        form.instance.sender = self.request.user
        ref = form.cleaned_data['ref']

        data = requests.get('https://ourfarms.herokuapp.com/apiRest/REF/?ref=' + ref,
                            auth=('GR3', 'gr3124567890')).json()

        contenidors = []
        if data:
            for contenidor in data[0]['Products']:
                cont = Contenidor(**contenidor)
                cont.save()
                contenidors.append(cont)
                if not data[0]['withdrawal']:
                    createTask(contenidor)
                else:
                    createTask2(contenidor)

            del data[0]['Products']

            man = Manifesto(**data[0])
            man.save()
            for contenidor in contenidors:
                man.products.add(contenidor)

        return redirect(reverse('storageandgo:gestor_arealizar'))


############################################ GESTOR SALA ##############################################################

@login_required()
def gestor_home(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-home.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


def gestor_arealizar(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-a-realizar.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


@login_required()
def gestor_realizando(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-realizando.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


@login_required()
def gestor_finalizado(request):
    # getting our template
    template = loader.get_template('Gestor_Sala/gestor-sala-finalizado.html')

    # rendering the template in HttpResponse
    return HttpResponse(template.render())


@login_required()
def mapa_salas(request):
    rooms = Room.objects.all()
    colors ={}
    group = User.objects.get(username=request.user).groups.all()[0]
    i = 1
    for room in rooms:
        if room.contenidorsInside /room.capacity > 0.50:
            colors['color'] = "w3-yellow"
        if room.contenidorsInside /room.capacity > 0.75:
            colors['color'] = "w3-orange"
        if room.contenidorsInside /room.capacity < 0.50:
            colors['color'] = "w3-green"
        i = i +1
    # rendering the template in HttpResponse
    if group.name == "Ceo":
        return render(request, "mapa-salas2.html", {'rooms': rooms})
    return render(request, "mapa-salas.html", {'rooms': rooms})


################################################# SALA ###############################################################


@login_required()
def CreateSalaView(request):
    if request.method == 'POST':
        form = CreateSala(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.save()
            return redirect('storageandgo:mapa_salas')
    else:
        form = CreateSala()
        return render(request, "form.html", {'form': form})


class SalaModify(UpdateView):
    model = Room
    fields = '__all__'
    template_name = "form.html"

    def form_valid(self, form):
        form.instance.sender = self.request.user
        return super(SalaModify, self).form_valid(form)


############################################## OPERARI #################################################################


@login_required()
def operari_home(request):
    # getting our template
    template = loader.get_template('Operaris/operari-home.html')

    # rendering the template in HttpResponse
    # return HttpResponse(template.render())
    return render(request, "Operaris/operari-home.html", {})


@login_required()
def operari_arealitzar(request):
    template = loader.get_template('Operaris/operari-a-realitzar.html')

    tasques_operari_a_realitzar = TaskOperator.objects.filter(accepted=False)
    context = {'tasques_operari_a_realitzar': tasques_operari_a_realitzar}

    # return HttpResponse(template.render(context))
    return render(request, "Operaris/operari-a-realitzar.html", context=context)


@login_required()
def operari_realizando(request):
    template = loader.get_template('Operaris/operari-realizando.html')

    tasques_operari_realizando = TaskOperator.objects.filter(accepted=True, finished=False, user=request.user)
    context = {'tasques_operari_realizando': tasques_operari_realizando}

    return render(request, "Operaris/operari-realizando.html", context=context)


@login_required()
def operari_finalizado(request):
    template = loader.get_template('Operaris/operari-finalizado.html')

    tasques_operari_finalizado = TaskOperator.objects.filter(finished=True, user=request.user)
    context = {'tasques_operari_finalizado': tasques_operari_finalizado}

    return render(request, "Operaris/operari-finalizado.html", context=context)


def operari_notification(request):
    current_user = request.user.id
    task = Task.objects.filter(user=current_user, high_priority=True, finished=False)

    if task.exists():
        return HttpResponse(task[0].pk)
    else:
        return HttpResponse("-1")


def operari_detall_tasca(request, pk):
    task = TaskOperator.objects.get(id=pk)
    return render(request, 'Operaris/operari-detall-tasca.html', {'tasca': task})

############################################### TECNIC #################################################################


@login_required()
def tecnics_home(request):
    template = loader.get_template('Tecnics/tecnics-home.html')

    return render(request, "Tecnics/tecnics-home.html")
@login_required()
def CreateAvariaView(request):
    if request.method == 'POST':
        form = CreateAvaria(request.POST)
        if form.is_valid():
            model_instance = form.save(commit=False)
            model_instance.save()
            return redirect('storageandgo:tecnics_home')
    else:
        form = CreateAvaria()
        return render(request, "form_tècnic.html", {'form': form})



class AvariaList(ListView):
    template_name = 'avaria_list.html'

    def get_context_data(self, **kwargs):
        context = super(AvariaList, self).get_context_data(**kwargs)
        avaria = Avaria.objects.filter(accepted=False, user=requests.user)
        context['task_avaria'] = avaria
        return context

    def get_queryset(self):
        queryset = Avaria.objects.filter()

        return queryset


@login_required()
def tecnics_arealitzar(request):
    template = loader.get_template('Tecnics/tecnics-a-realizar.html')

    tasques_tecnics_a_realitzar = TaskMaintenance.objects.filter(accepted=False)
    context = {'tasques_tecnics_a_realitzar': tasques_tecnics_a_realitzar}

    return render(request, "Tecnics/tecnics-a-realizar.html", context=context)


@login_required()
def tecnics_realizando(request):
    template = loader.get_template('Tecnics/tecnics-realizando.html')

    tasques_tecnics_realizando = TaskMaintenance.objects.filter(accepted=True, finished=False, user=request.user)
    context = {'tasques_tecnics_realizando': tasques_tecnics_realizando}

    return render(request, "Tecnics/tecnics-realizando.html", context=context)


@login_required()
def tecnics_finalizado(request):
    template = loader.get_template('Tecnics/tecnics-finalitzades.html')

    tasques_tecnics_finalitzades = TaskMaintenance.objects.filter(finished=True, user=request.user)
    context = {'tasques_tecnics_finalitzades': tasques_tecnics_finalitzades}

    return render(request, "Tecnics/tecnics-finalitzades.html", context=context)


def tecnics_detall_tasca(request, pk):
    task = TaskMaintenance.objects.get(id=pk)
    return render(request, 'Tecnics/tecnics-detall-tasca.html', {'tasca': task})

################################################# TASKS ################################################################
class ListUnasignedTasks(ListView):
    template_name = 'unasigned_task_list.html'

    def get_context_data(self, **kwargs):
        context = super(ListUnasignedTasks, self).get_context_data(**kwargs)
        operator = TaskOperator.objects.filter(user=None)
        maintenance = TaskMaintenance.objects.filter(user=None)
        context['unasigned_operator'] = operator
        context['unasigned_maintenance'] = maintenance
        return context

    def get_queryset(self):

StorageAndGo/templates/avaria_list.html
{% extends "ceo/ceo-home.html" %}
{% block content %}

    <h1>LIST OF ISSUES</h1><br>

    {% for task in task_avaria %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.object }} - <a href="{% url 'storageandgo:accept_task' task.pk %}">Acceptar</a>
            <a href="{% url 'storageandgo:modify_avaria' task.pk %}">Editar</a>
        </h3><br>
    {% endfor %}



{% endblock %}

StorageAndGo/templates/form.html
{% extends "Gestor_Sala/gestor-sala-home.html" %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="hidden" name="next" value="{{ request.path }}"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

StorageAndGo/templates/form_tècnic.html
{% extends "Tecnics/tecnics-home.html" %}
{% block content %}
    <form method="post" action="">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="hidden" name="next" value="{{ request.path }}"/>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}

StorageAndGo/templates/gestor-sala-finalizado.html
{% extends 'gestor-sala-home.html' %}
{% block content %}

    <h1>LIST OF OPERATOR TASKS</h1><br>

    {% for task in task_operator %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.product }}
        </h3><br>
    {% endfor %}

    <h1>LIST OF MAINTENANCE TASKS</h1><br>

    {% for task in task_maintenance %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.product }}
        </h3><br>
    {% endfor %}

{% endblock %}

StorageAndGo/templates/gestor-sala-realizando.html
{% extends 'gestor-sala-home.html' %}
{% block content %}

    <h1>LIST OF OPERATOR TASKS</h1><br>

    {% for task in task_operator %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.product }} - <a href="{% url 'storageandgo:finish_task' task.pk %}">Finalitzar</a>
        </h3><br>
    {% endfor %}

    <h1>LIST OF MAINTENANCE TASKS</h1><br>

    {% for task in task_maintenance %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.product }} - <a href="{% url 'storageandgo:finish_task' task.pk %}">Finalitzar</a>

        </h3><br>
    {% endfor %}

{% endblock %}

StorageAndGo/templates/info_sala.html
{% extends 'Gestor_Sala/gestor-sala-home.html' %}
{% block content %}
    <a href='{% url "storageandgo:mapa_salas" %}'>
        <button class="w3-button w3-green" style="width: 100px; height: 50px; margin: 15px">VOLVER</button>
    </a>
    <h1 style="text-transform: uppercase"> SALA {{ sala.name }}</h1>
    <ul>
        <li><b> {{ sala.pk }} </b></li>
        <li><b>CONTENEDORES: </b> {{ sala.contenidorsInside }}/{{ sala.capacity }}</li>
        <li><b>HUMEDAD MAXIMA: </b> {{ sala.humitMin }}%</li>
        <li><b>HUMEDAD MINIMA: </b> {{ sala.humitMax }}%</li>
        <li><b>TEMPERATURA MAXIMA: </b> {{ sala.temperatureMin }}ºC</li>
        <li><b>TEMPERATURA MAXIMA: </b> {{ sala.temperatureMax }}ºC</li>
        <li><b>DESCRIPCION: </b> {{ sala.description }}</li>
    </ul>
    <a href='{% url "storageandgo:modify_sala" sala.pk %}'>
        <button class="w3-button w3-grey" style="width: 100px; height: 50px; margin: 15px">EDITAR</button>
    </a>
    {% if sala.contenidorsInside == 0 %}
    <a href='{% url "storageandgo:sala_delete" sala.pk %}'>
        <button class="w3-button w3-red" style="width: 100px; height: 50px; margin: 15px">ELIMINAR</button>
    </a>
    {% endif %}
{% endblock %}

StorageAndGo/templates/info_sala2.html
{% extends 'ceo/ceo-home.html' %}
{% block content %}
    <a href='{% url "storageandgo:mapa_salas" %}'>
        <button class="w3-button w3-green" style="width: 100px; height: 50px; margin: 15px">VOLVER</button>
    </a>
    <h1 style="text-transform: uppercase"> SALA {{ sala.name }}</h1>
    <ul>
        <li><b>SALA: </b> </b> {{ sala.pk }}</li>
        <li><b>CONTENEDORES: </b> {{ sala.contenidorsInside }}/{{ sala.capacity }}</li>
        <li><b>HUMEDAD MAXIMA: </b> {{ sala.humitMin }}%</li>
        <li><b>HUMEDAD MINIMA: </b> {{ sala.humitMax }}%</li>
        <li><b>TEMPERATURA MAXIMA: </b> {{ sala.temperatureMin }}ºC</li>
        <li><b>TEMPERATURA MAXIMA: </b> {{ sala.temperatureMax }}ºC</li>
        <li><b>DESCRIPCION: </b> {{ sala.description }}</li>
    </ul>
{#    <a href='{% url "storageandgo:modify_sala" sala.pk %}'>#}
{#        <button class="w3-button w3-grey" style="width: 100px; height: 50px; margin: 15px">EDITAR</button>#}
{#    </a>#}
{#    <a href='{% url "storageandgo:sala_delete" sala.pk %}'>#}
{#        <button class="w3-button w3-red" style="width: 100px; height: 50px; margin: 15px">ELIMINAR</button>#}
{#    </a>#}
{% endblock %}

StorageAndGo/templates/mapa-salas.html
{% extends 'Gestor_Sala/gestor-sala-home.html' %}

    {% block content %}
        <h1> SALAS </h1>

            {% for sala in rooms %}
               {% if sala.percent_ocupation < 50 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-green" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b><br> {{ sala.contenidorsInside }}/{{ sala.capacity }} <br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
               {% if sala.percent_ocupation >= 50 and sala.percent_ocupation < 75 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-yellow" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }}<br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
               {% if sala.percent_ocupation >= 75 and sala.percent_ocupation < 100 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-orange" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }}<br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
               {% if sala.percent_ocupation >= 100 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-red" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }} <br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
            {% endfor %}

            <a href= {% url 'storageandgo:afegir_sala' %}><button class="w3-button w3-circle w3-black w3-display-bottomright"style="position: fixed; width:1.5cm; height:1.5cm; margin-right: 2%; margin-bottom: 2%">+</button></a>
    {% endblock %}

StorageAndGo/templates/mapa-salas2.html
{% extends 'ceo/ceo-home.html' %}

    {% block content %}
        <h1> SALAS </h1>

            {% for sala in rooms %}
               {% if sala.percent_ocupation < 50 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-green" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }} <br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
               {% if sala.percent_ocupation >= 50 and sala.percent_ocupation < 75 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-yellow" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }}<br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
               {% if sala.percent_ocupation >= 75 and sala.percent_ocupation < 100 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-orange" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }}<br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
               {% if sala.percent_ocupation >= 100 %}
                   <a href='{% url "storageandgo:sala_detail" sala.pk %}'><button class="w3-button w3-red" style="width: 120px; height: 120px; margin: 15px"><b>SALA {{ sala.pk }} </b> <br> {{ sala.contenidorsInside }}/{{ sala.capacity }} <br>{{ sala.temperatureMin }}-{{ sala.temperatureMax }}ºC <br>{{ sala.humitMin }}-{{ sala.humitMax }}% </button></a>
               {% endif %}
            {% endfor %}

{#            <a href= {% url 'storageandgo:afegir_sala' %}><button class="w3-button w3-circle w3-black w3-display-bottomright"style="position: fixed; width:1.5cm; height:1.5cm; margin-right: 2%; margin-bottom: 2%">+</button></a>#}
    {% endblock %}

StorageAndGo/templates/operari-a-realitzar.html
{% extends 'operari-home.html' %}

    {% block content %}
        <h3>Llista tasques a realitzar:</h3>
        {% if tasques_operari_a_realitzar %}
            <ul>
                {% for task in tasques_operari_a_realitzar %}
                    <a href="#">{{ task.description }}</a> - <a href="{% url 'storageandgo:accept_task' task.pk %}">Acceptar</a> / <a href="{% url 'storageandgo:modify_operator' task.pk %}">Editar</a>
                {% endfor %}
            </ul>
        {% endif %}
    {% endblock %}

StorageAndGo/templates/operari-realizando.html
{% extends 'operari-home.html' %}

    {% block content %}
        <h3>Lista tareas realizando:</h3>
        {% if tasques_operari_realizando %}
            <ul>
                {% for task in tasques_operari_realizando %}
                    <a href="#">{{ task.description }}</a> - <a href="{% url 'storageandgo:finish_task' task.pk %}">Finalizar</a> / <a href="{% url 'storageandgo:accept_task' task.pk %}"></a>
                {% endfor %}
            </ul>
        {% endif %}
    {% endblock %}

StorageAndGo/templates/tecnics-finalitzades.html
{% extends 'tecnics-home.html' %}

    {% block content %}
        <h3>Llista tasques finalitzades manteniment:</h3>
        {% if tasques_tecnics_finalitzades %}
            <ul>
                {% for task in tasques_tecnics_finalitzades %}
                    <a href="#">{{ task.description }}</a>
                {% endfor %}
            </ul>
        {% endif %}
    {% endblock %}

StorageAndGo/templates/tecnics-realizando.html
{% extends 'tecnics-home.html' %}

    {% block content %}
        <h3>Llista tasques realitzant manteniment:</h3>
        {% if tasques_tecnics_realizando %}
            <ul>
                {% for task in tasques_tecnics_realizando %}
                    <a href="#">{{ task.description }}</a> - <a href="{% url 'storageandgo:finish_task' task.pk %}">Finalitzar</a>
                {% endfor %}
            </ul>
        {% endif %}
    {% endblock %}

StorageAndGo/templates/unasigned_task_list.html
{% extends "Gestor_Sala/gestor-sala-home.html" %}
{% block content %}

    <h1>LIST OF OPERATOR UNASIGNED TASKS</h1><br>

    {% for task in unasigned_operator %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.product }} - <a href="{% url 'storageandgo:assign_task' task.pk %}">Assignar</a> </h3><br>
    {% endfor %}

    <h1>LIST OF MAINTENANCE UNASIGNED TASKS</h1><br>

    {% for task in unasigned_maintenance %}
        <h3>{{ task.pk }} - {{ task.description }} - {{ task.product }} - <a href="{% url 'storageandgo:assign_task' task.pk %}">Assignar</a> </h3><br>
    {% endfor %}

{% endblock %}